actor_learning_rate: 0.0003
alpha_learning_rate: 0.0003
batch_size: 256
buffer_size: 1000000
checkpoints_path: ./models/sac-n\SAC-N-MiniGrid-FourRooms-v1-4e782860
critic_learning_rate: 0.0003
deterministic_torch: false
device: cuda
env_name: MiniGrid-FourRooms-v1
eval_episodes: 40
eval_every: 50
eval_seed: 42
gamma: 0.99
group: SAC-N
hidden_dim: 256
log_every: 100
max_action: 1.0
name: SAC-N-MiniGrid-FourRooms-v1-4e782860
normalize_reward: false
num_critics: 2
num_epochs: 20
num_updates_on_epoch: 10
project: SAC-N
tau: 0.005
train_seed: 10
