actor_learning_rate: 0.0003
alpha_learning_rate: 0.0003
batch_size: 256
beta: 1
buffer_size: 1000000
checkpoints_path: ./models/sac_bc/optimal_4862e6de
critic_learning_rate: 0.0003
deterministic_torch: false
device: cuda
env_name: MiniGrfid-FourRooms-v1
eval_episodes: 40
eval_every: 50
eval_seed: 1
gamma: 0.99
group: SAC-N
hidden_dim: 256
log_every: 100
max_action: 1.0
name: 4862e6de
normalize_reward: false
num_critics: 2
num_epochs: 20
num_updates_on_epoch: 10
project: SAC-N
tau: 0.005
train_seed: 0
